name: 'Build from comment'
on:
    push:

jobs:
        one:
            runs-on: ubuntu-latest
            steps:
                - name: 'Dump GitHub context'
                  
                  run: echo "TEST"

                  